# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Descripcion', models.CharField(max_length=300)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='idSucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Sucursal'),
        ),
    ]
