# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-21 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item3', models.CharField(max_length=70)),
                ('item4', models.DateField()),
            ],
        ),
    ]
