# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-21 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0002_prueba2'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba2',
            name='item5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hola.prueba'),
            preserve_default=False,
        ),
    ]
