# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0004_auto_20180821_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='img')),
            ],
        ),
    ]
