# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-04 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0006_auto_20180828_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='img')),
                ('imagen2', models.ImageField(upload_to='img')),
            ],
        ),
    ]
